[package]
name = "rsbot"
version = "0.1.0"
authors = ["Will Eccles <will@eccles.dev>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
discord = "0.8.1"
